run:
  modules-download-mode: readonly 
  go: "1.24" 

linters-settings:
  varnamelen:
    ignore-decls:
      - c *gin.Context
      - s *PlayService
      - s *AuthService
      - s *ManageService  
      - h *handlers.ManageHandler  
      - h *handlers.AuthHandler
      - h *handlers.PlayHandler
      - ok bool

  funlen:
    lines: 80

  gosec:
    excludes:
      - G404

linters:
  enable-all: true
  disable:
    - tenv #DEPRECATED
    - depguard #BUG WITH IMPORTS
    - exhaustruct #hren polnaya
    - mnd # magic numbers nadoel
    - gci # conflict with gofumpt
    - gofumpt # disabled cause of gofumpt was integrated in golang
    - godox # TODO/BUG/FIXME ya zdec uzau
    - nlreturn #netu iskluchenii dlya loggera pered returnom
    - wsl # like nlreturn
issues:
  exclude-rules:
    - path: ".*_test.go" 
      linters:
        - gomnd
    - text: "TODO"       
      linters:
        - lll
  max-issues-per-linter: 0 
  max-same-issues: 0       
