services:
  goapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DATABASE_HOST:-postgres}
      DB_USER: ${DATABASE_USER:-appuser}
      DB_PASSWORD: ${DATABASE_PASSWORD:-secret}
      DB_NAME: ${DATABASE_NAME:-appdb}
      DB_PORT: ${DATABASE_PORT:-5432}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/00-init.sql
      - ./sql/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    environment:
      POSTGRES_USER: ${DATABASE_USER:-appuser}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-secret}
      POSTGRES_DB: ${DATABASE_NAME:-appdb}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5431:5431"

volumes:
  postgres_data: